// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsAggregator.Infrastructure.Data;

#nullable disable

namespace NewsAggregator.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260726154022_AddNewsImageUrl")]
    partial class AddNewsImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("NewsAggregator.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Политические новости",
                            Icon = "🏛️",
                            Name = "Политика"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Экономика и финансы",
                            Icon = "💹",
                            Name = "Экономика"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Спортивные события",
                            Icon = "⚽",
                            Name = "Спорт"
                        },
                        new
                        {
                            Id = 4,
                            Description = "IT и технологии",
                            Icon = "💻",
                            Name = "Технологии"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Научные открытия",
                            Icon = "🔬",
                            Name = "Наука"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Культура и искусство",
                            Icon = "🎭",
                            Name = "Культура"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Медицина и здоровье",
                            Icon = "🏥",
                            Name = "Здоровье"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Бизнес и предпринимательство",
                            Icon = "💼",
                            Name = "Бизнес"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Окружающая среда",
                            Icon = "🌿",
                            Name = "Экология"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Кино, музыка, игры",
                            Icon = "🎬",
                            Name = "Развлечения"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Наука и образование",
                            Icon = "📚",
                            Name = "Образование"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Туризм и путешествия",
                            Icon = "✈️",
                            Name = "Путешествия"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Разное",
                            Icon = "📰",
                            Name = "Другое"
                        });
                });

            modelBuilder.Entity("NewsAggregator.Core.Entities.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("News");
                });

            modelBuilder.Entity("NewsAggregator.Core.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("NewsAggregator.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NewsAggregator.Core.Entities.UserPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("NewsAggregator.Core.Entities.UserReadHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewsId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NewsId");

                    b.HasIndex("UserId");

                    b.ToTable("UserReadHistories");
                });

            modelBuilder.Entity("NewsAggregator.Core.Entities.News", b =>
                {
                    b.HasOne("NewsAggregator.Core.Entities.Category", "Category")
                        .WithMany("News")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NewsAggregator.Core.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("NewsAggregator.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewsAggregator.Core.Entities.UserPreference", b =>
                {
                    b.HasOne("NewsAggregator.Core.Entities.User", "User")
                        .WithMany("Preferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewsAggregator.Core.Entities.UserReadHistory", b =>
                {
                    b.HasOne("NewsAggregator.Core.Entities.News", "News")
                        .WithMany()
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsAggregator.Core.Entities.User", "User")
                        .WithMany("ReadHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("News");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewsAggregator.Core.Entities.Category", b =>
                {
                    b.Navigation("News");
                });

            modelBuilder.Entity("NewsAggregator.Core.Entities.User", b =>
                {
                    b.Navigation("Preferences");

                    b.Navigation("ReadHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
